#
# Database Configuration File
#

mongo:
  connection_string: "" #Removed connection string for security reasons
  database: "minecraft"
splunk:
  host: "10.0.0.148"
  username: "minecraft"
  password: "Minecraft!"
  scheme: "https"
  port: 8089
